# Generated by Django 4.1.7 on 2023-04-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TAScheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="home_address",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="office_hours",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
