# Generated by Django 4.1.7 on 2023-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TAScheduler", "0002_useraccount_alter_course_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="type",
            field=models.CharField(
                choices=[
                    ("TA", "TA"),
                    ("INSTRUCTOR", "Instructor"),
                    ("ADMIN", "Admin"),
                ],
                max_length=32,
            ),
        ),
    ]
