# Generated by Django 4.1.7 on 2023-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TAScheduler", "0003_alter_useraccount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="number",
            field=models.CharField(default="COMPSCI 361", max_length=128),
            preserve_default=False,
        ),
    ]
