# Generated by Django 4.1.7 on 2023-04-26 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TAScheduler", "0005_alter_section_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="name",
            new_name="number",
        ),
    ]
