from .view_create_user import CreateUser
from .view_home import Home
from .view_login import Login
from .view_logout import Logout
from .view_create_section import CreateSection
from .view_create_course import CreateCourse
from .view_accounts import Accounts
from .view_sections import Sections
from .view_edit_user import EditUser
from .view_edit_section import EditSection
from .view_delete_user import DeleteUser
from .view_modify_account import ModifyAccount
from .view_add_section_ta import AddSectionTA
from .view_courses import Courses
